version: 2

sources:
  - name: conformed
    database: raw
    schema: conformed

    tables:
      - name: DateDimension
        columns:
          - name: DateKey
            tests:
              - unique

  - name: pubs
    database: raw
    schema: pubs

    tables:
      - name: Authors
        columns:
          - name: au_id
            tests:
              - unique
              - not_null

      - name: Employee
        columns: 
          - name: emp_id
            tests:
              - unique
          - name: job_id
            tests:
              - not_null
          - name: pub_id 
            tests:
              - not_null

      - name: Jobs
        columns:
          - name: job_id
            tests:
              - unique 
              - not_null

      - name: Publishers
        columns:
          - name: pub_id
            tests:
              - unique 
              - not_null

      - name: Pub_Info
        columns:
          - name: pub_id
            tests:
              - not_null

      - name: Sales
        columns:
          - name: stor_id
            tests:
              - not_null
          - name: title_id
            tests:
              - not_null
      
      - name: Stores
        columns:
          - name: stor_id
            tests:
              - unique   

      - name: TitleAuthor
        columns:
          - name: au_id
            tests:
              - not_null
          - name: title_id
            tests:
              - not_null

      - name: Titles
        columns:
          - name: title_id
            tests:
              - unique